# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zghouzla <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/16 19:58:05 by zghouzla          #+#    #+#              #
#    Updated: 2021/11/23 23:39:50 by zghouzla         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


SRCS		= ft_atoi.c    ft_isascii.c ft_memcpy.c  ft_strlcat.c ft_strrchr.c \
		  	ft_bzero.c   ft_isdigit.c ft_memmove.c ft_strlcpy.c ft_tolower.c \
		  	ft_calloc.c  ft_isprint.c ft_memset.c  ft_strlen.c  ft_toupper.c \
		  	ft_isalnum.c ft_memchr.c  ft_strchr.c  ft_strncmp.c ft_isalpha.c \
		  	ft_memcmp.c  ft_strdup.c  ft_strnstr.c  ft_itoa.c  ft_putchar_fd.c \
			ft_putendl_fd.c  ft_putnbr_fd.c  ft_putstr_fd.c  ft_split.c  ft_strjoin.c \
			ft_strtrim.c  ft_substr.c  ft_strmapi.c  ft_striteri.c \

OBJS		= $(SRCS:.c=.o)

%.o: %.c
			$(CC) $(CFLAGS) -c $< -o $@

NAME		= libft.a

CC			= gcc

CFLAGS		= -Wall -Wextra -Werror

RM			= rm -f

all:		$(NAME)

$(NAME):	$(OBJS)
			ar rcs $(NAME) ${OBJS}

clean:
			${RM} ${OBJS}

fclean:		clean
			${RM} $(NAME)

re : 		fclean $(NAME)

.PHONY:		all clean fclean re
